# docker-compose.yml

version: '3.7'
services: 
  app:
    container_name: app
    depends_on: 
      - db
    ports:
      - ${PORT}
    volumes:
      # i may be holding two storages of the volume data in both containers for the vue data
      - .:/app/
      - /app/node_modules/
      - front_end_build:/app/dist/
    build: .
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: npower.app
      VIRTUAL_PORT: ${PORT}
      NODE_ENV: development
    command: "npm run dev"
    networks:
      - nginx-proxy
      - backend
      - frontend
  
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "4306:3306" #remove this for production
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - backend

  webpack:
    container_name: webpack
    image: npower_app
    depends_on: 
      - app
    volumes:
      - ./webpack.config.dev.js:/app/webpack.config.dev.js #need to copy in the webpack file 
      - ./vue:/app/vue/   #this volume is to sync the cource files up so changes can be mirrored in the docker container
      - front_end_build:/app/dist/  #this is probably needed once webpack has html copied over
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: npower.app
    env_file:
      - .env
    command: "npm run watch"
    networks:
      - frontend

volumes:
  front_end_build:

networks:
  backend:
  frontend:
  nginx-proxy:
    external: true


