# docker-compose.yml

version: '3'
services: 
  app:
    container_name: app
    depends_on: 
      - db
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    restart: always
  
  db:
    container_name: db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret

