# docker-compose.yml

version: '3'
services: 
  app:
    container_name: app
    depends_on: 
      - db
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=development
  
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "4306:3306" #remove this for production
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env