# docker-compose.yml

version: '3.3'
services: 
  app:
    container_name: app
    depends_on: 
      - db
    ports:
      - ${PORT}
    volumes:
      - .:/app/
      - front_end_build:/app/dist/
      - node_modules:/app/node_modules/
    build: .
    env_file:
      .env
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    command: ${COMMAND}
    networks:
      - nginx-proxy
      - backend
      - frontend
  
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      .env
    environment:
      PORT: ${MYSQL_PORT}
    networks:
      - backend

  webpack:
    container_name: webpack
    image: npower_app
    depends_on: 
      - app
    volumes:
      # - ./${WEBPACK_FILE}:/app/${WEBPACK_FILE} #need to copy in the webpack file dev only
      - ./vue:/app/vue/   #this volume is to sync the cource files up so changes can be mirrored in the docker container
      - front_end_build:/app/dist/  #this is probably needed once webpack has html copied over
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
    command: ${COMMAND_WEBPACK}
    networks:
      - frontend

volumes:
  front_end_build:
  node_modules:

networks:
  backend:
  frontend:
  nginx-proxy:
    external: true


